### ISSUE TITLE
找到一个第三方驱动，道友可以试试

### ISSUE THREAD

**Issue by metitation** [3Alan/Hackintosh-i510400-B460M-MORTAR-WIFI#2]
https://github.com/OpenIntelWireless/itlwm

https://zhuanlan.zhihu.com/p/319659227

**Comment by 3Alan** [comment]
感谢，我用的就是这个。不过最近好像稳定多了。我有一个蓝牙音箱，发现在windows/mac中只能连接上其中一个

**Comment by metitation** [comment]
就是说，如果我知识装单Mac OS ，这套硬件可以做到完美黑、？

**Comment by 3Alan** [comment]
完美我觉得还是差点的，你可以主板换非wifi版的然后买一个黑苹果专用网卡可能体验会更好
