### ISSUE TITLE
主板一样，用了efi，wifi无法使用，蓝牙正常

### ISSUE THREAD

**Issue by Minor-fun** [3Alan/Hackintosh-i510400-B460M-MORTAR-WIFI#4]
我的配置也是10400+b460m mortar-wifi，镜像是黑果小兵的13.2.1三分区版本，装上其他的正常，发现wifi用不了，请问下是有其他地方要设置一下吗

**Comment by 3Alan** [comment]
是wifi打不开还是wifi连不上？

**Comment by 3Alan** [comment]
我使用一周下来的体验：wifi不太稳定。如果你是用作生产机的话最好换黑苹果专用网卡或者是直接插网线

**Comment by Minor-fun** [comment]
![TIM图片20210620205632](https://user-images.githubusercontent.com/45744798/122674972-03c9e100-d20a-11eb-97ee-569418d3d632.png)
![TIM图片20210620205643](https://user-images.githubusercontent.com/45744798/122674981-0af0ef00-d20a-11eb-9758-95bbf0b2d908.png)
![2AA9F9BBA2F2B3F2B92D86A26F1EAF7B](https://user-images.githubusercontent.com/45744798/122674984-0cbab280-d20a-11eb-9d10-2c44ef1445ec.JPG)
![D2FE2816067C0DEBECA0B551D06D0BFC](https://user-images.githubusercontent.com/45744798/122674988-0e847600-d20a-11eb-90b9-1200273f4e98.JPG)
像这样，打开了，什么都没有，，，

**Comment by Minor-fun** [comment]
然后网络设置那里只有以太网络，没有wifi，，，

**Comment by 3Alan** [comment]
https://github.com/3Alan/Hackintosh-i510400-B460M-MORTAR-WIFI/releases
你是从这下载的EFI吗

**Comment by Minor-fun** [comment]
对，是从这里下载的

**Comment by 3Alan** [comment]
你如果和我一样也是windows/mac双系统的话：
1. 确认windows中你的wifi是否能够使用
2. 如果能够使用的话参考我文档中提到的“wifi无法冷启动”解决方案

如果只是单Mac的话，我就不太清楚了（我刚折腾黑苹果也没多久）。

**Comment by 3Alan** [comment]
你如果和我一样也是windows/mac双系统的话：
1. 确认windows中你的wifi是否能够使用
2. 如果能够使用的话参考我文档中提到的“wifi无法冷启动”解决方案

如果只是单Mac的话，我就不太清楚了（我刚折腾黑苹果也没多久）。

**Comment by Minor-fun** [comment]
![9B28537865D071F132491AB3F632EFCC](https://user-images.githubusercontent.com/45744798/122793239-8a0b2380-d2ed-11eb-85b5-b7dc4f25d763.JPG)
一个奇怪的问题，按照你的提示，我将EFI下的Microsoft文件夹放到了系统上的efi分区上，添加后，wifi可以正常使用，好奇怪，不过这个问题解决了，只需要将efi原封不动的放进去就可以。不用删除EFI里的Microsoft文件夹。
